### ISSUE TITLE
如何实现手机九宫格输入法下的单字组词

### ISSUE THREAD

**Issue by faywong** [JaaikoLai/rime_pure#125]
**Is your feature request related to a problem? Please describe.**
众所周知，九宫格输入法重码率更高，且一般的手机九宫格输入法都提供了单字组词功能。
![image](https://github.com/SivanLaai/rime-pure/assets/1934627/148c740f-37da-460f-aa53-ec5da1e7320d)

**Describe the solution you'd like**
希望在九宫格输入法的时候具备单字组词能力。

**Additional context**
我并不是伸手发请求，更希望各位专家能提供相关的 Rime 知识背景/思路，然后自己去实现。回馈给社区。

**Comment by bandengzex** [comment]
在群里问过很多老大  都说是rime的限制 不可能实现。我也是九宫使用者，对这个的需求感也挺高的，我的想法是通过流体键盘+lua实现。但是我不会写lua代码。。。但是我感觉既然能实现九宫候选显示拼音应该是能lua实现的

**Comment by dashu1995** [comment]
> 在群里问过很多老大 都说是rime的限制 不可能实现。我也是九宫使用者，对这个的需求感也挺高的，我的想法是通过流体键盘+lua实现。但是我不会写lua代码。。。但是我感觉既然能实现九宫候选显示拼音应该是能lua实现的

我想进入这个群，一直找不到群号，可否留给我QQ群号，谢谢
