### ISSUE TITLE
符号问题

### ISSUE THREAD

**Issue by zoeins** [JaaikoLai/rime_pure#43]
怎么使用符号，我没研究明白，谢谢指导

**Comment by SivanLaai** [comment]
你是指新加入的剪切板和符号吗

**Comment by zoeins** [comment]
不是，配置文件里显示例如  /jq
出来的应该是节气，但我输入“/”就直接在文本里了，不是上屏，导致没办法跟后续的请求有联系，不知你是否明白我的说法，这应该是我的配置文件或者操作不当，不知道怎么改正

Sivan ***@***.***> 于 2021年10月19日周二 10:22写道：

**Comment by SivanLaai** [comment]
方案必须保证中文半角，中文符号输入，并且必须是正常的中文输入模式（也就是可以可以正常使用方案的模式下）。
