### ISSUE TITLE
"以为"的拼音出现"也有"的词语

### ISSUE THREAD

**Issue by zoeins** [JaaikoLai/rime_pure#44]
![IMG_20211020_042621](https://user-images.githubusercontent.com/85345080/137985910-e94a70b7-b33f-45c6-bc63-98cae7495dfa.jpg)
这是否是bug？

**Comment by zoeins** [comment]
一起让项目变得更好，我特殊符号还是不怎么会使用，就成功过一次

Sivan ***@***.***> 于 2021年10月20日周三 15:21写道：

**Comment by zoeins** [comment]
输入后显示的是“、”

Sivan ***@***.***> 于 2021年10月20日周三 15:43写道：

**Comment by zoeins** [comment]
我找到原因了，四叶草简体拼音确实有这个问题，现在用极点五笔就可以正常输入和显示。

Sivan ***@***.***> 于 2021年10月20日周三 16:33写道：

**Comment by SivanLaai** [comment]
把项目下下来，从[源文件](https://github.com/SivanLaai/rime-pure/tree/master/schemes/Clover%E5%9B%9B%E5%8F%B6%E8%8D%89%E6%8B%BC%E9%9F%B3)直接获取

**Comment by zoeins** [comment]
试过了，我刚刚下载了你打包好的版本也不行，直接下载源文件也不行，不折腾了 ，五笔可以出来特殊符号，刚好我也想学习下五笔。

Sivan ***@***.***> 于 2021年10月20日周三 16:46写道：

**Comment by SivanLaai** [comment]
https://github.com/SivanLaai/rime-pure/releases/tag/1.1.6
